# The default build for wasp-os. Modify to customize your own build.
# At least one watch face must be specified. Quick ring apps will be added in order.

[[app]]
file = 'apps/mood.py'
quick_ring = true

[[app]]
file = 'apps/milestone.py'
quick_ring = true

[[app]]
file = 'apps/space_font.py'
auto_load = true

[[app]]
file = 'apps/bubble_font.py'

[[app]]
file = 'apps/digi_font.py'

#[[app]]
#file = 'apps/scifi_font.py'

[[app]]
file = 'apps/snake.py'

#[[app]]
#file = 'apps/heart.py'

#[[app]]
#file = 'apps/calculator.py'

#[[app]] # If only one watch face is included this app can be removed
#file = 'apps/faces.py'
#auto_load = true
#no_except = true

[[watchface]]
file = 'watch_faces/monolith.py'
default = true

#[[watchface]]
#file = 'watch_faces/clock.py'

#[[watchface]] # Requires ClockApp to also be installed
#file = 'watch_faces/week_clock.py'

#[[watchface]]
#file = 'watch_faces/chrono.py'

